name: Docker

on:
  workflow_call:
    inputs:
      build:
        default: true
        required: false
        type: boolean
      region:
        required: true
        type: string
    outputs:
      application:
        value: ${{ jobs.docker.outputs.application }}
      image:
        value: ${{ jobs.docker.outputs.image }}
      registry:
        value: ${{ jobs.docker.outputs.registry }}
      tag:
        value: ${{ jobs.docker.outputs.tag }}
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest

    outputs:
      application: ${{ steps.retrieve.outputs.application }}
      image: ${{ steps.push.outputs.image }}
      registry: ${{ steps.login.outputs.registry }}
      tag: ${{ steps.retrieve.outputs.tag }}

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build docker image
        id: build
        if: inputs.build == true
        run: echo "::set-output name=sha::$(docker build --quiet .)"

      - name: Retrieve application and tag
        id: retrieve
        run: |
          echo "::set-output name=application::$(basename $GITHUB_REPOSITORY)"
          echo "::set-output name=tag::$(git describe --always)"

      - name: Create ECR repository (if not exist)
        # env:
        #   REPOSITORY: ${{ steps.retrieve.outputs.application }}
        run: aws ecr create-repository --repository-name ${{ steps.retrieve.outputs.application }} || true

      - name: Tag and push docker image to ECR
        id: push
        env:
          APPLICATION: ${{ steps.retrieve.outputs.application }}
          REGISTRY: ${{ steps.login.outputs.registry }}
          SHA: ${{ steps.build.outputs.sha }}
          TAG: ${{ steps.retrieve.outputs.tag }}
        run: |
          image=$REGISTRY/$APPLICATION:$TAG
          docker tag $SHA $image
          docker push $image
          echo "::set-output name=image::$image"
