name: Reusable workflow example

on:
  workflow_call:

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Show environment
        run: env

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
