name: Render

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
    secrets:
      variables:
        required: false
    outputs:
      artifact:
        value: ${{ jobs.render.outputs.artifact }}

jobs:
  render:
    runs-on: ubuntu-latest

    outputs:
      artifact: ${{ steps.generate.outputs.file }}

    steps:
      - uses: actions/checkout@v2

      - name: Import variables to environment
        if: ${{ secrets.variables }} != null
        run: |
          echo "${{ secrets.variables }}" | while IFS= read -r variable
          do
            echo "$variable" >> $GITHUB_ENV
          done

      - name: Generate variables file
        id: generate
        run: |
          yaml=variables.yml
          json=variables.json
          envsubst < premierbloc.yml > $yaml
          python3 -c 'import sys, yaml, json; print(json.dumps(yaml.safe_load(sys.stdin.read())))' < $yaml > $json
          rm $yaml
          echo "::set-output name=file::$json"

      - name: Archive vairiables file
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: ${{ steps.generate.outputs.file }}
          path: ${{ steps.generate.outputs.file }}
          retention-days: 1
