name: Setup

on:
  workflow_call:
    outputs:
      application:
        value: ${{ jobs.setup.outputs.application }}
      environment:
        value: ${{ jobs.setup.outputs.environment }}
      tag:
        value: ${{ jobs.setup.outputs.tag }}

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      application: ${{ steps.retrieve.outputs.application }}
      environment: ${{ steps.retrieve.outputs.environment }}
      tag: ${{ steps.retrieve.outputs.tag }}

    steps:
      - uses: actions/checkout@v2

      - name: Retrieve application, environment and tag
        id: retrieve
        run: |
          ref=$(echo ${GITHUB_HEAD_REF:-$GITHUB_REF} | sed -e 's#refs/heads/##')
          case $ref in
              refs/tags/*   ) environment=production ;;
              main          ) environment=stage ;;
              *             ) environment=$(echo $ref | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          esac

          echo "::set-output name=environment::$environment"
          echo "::set-output name=application::$(basename $GITHUB_REPOSITORY)"
          echo "::set-output name=tag::$(git describe --always)"
